// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// ReadLaterRepository is an autogenerated mock type for the ReadLaterRepository type
type ReadLaterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: readLater
func (_m *ReadLaterRepository) Create(readLater entities.ReadLater) error {
	ret := _m.Called(readLater)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ReadLater) error); ok {
		r0 = rf(readLater)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: readLater
func (_m *ReadLaterRepository) Delete(readLater entities.ReadLater) error {
	ret := _m.Called(readLater)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ReadLater) error); ok {
		r0 = rf(readLater)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewReadLaterRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewReadLaterRepository creates a new instance of ReadLaterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReadLaterRepository(t mockConstructorTestingTNewReadLaterRepository) *ReadLaterRepository {
	mock := &ReadLaterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
