// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infras

import (
	"backend/handlers"
	"backend/repository"
	"backend/routes"
	"backend/services/role"
	"backend/services/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitizeUser(db *gorm.DB) *routes.UserRoutes {
	userRepo := repository.NewUserRepo(db)
	roleRepo := repository.NewRoleRepo(db)
	roleService := roleservice.NewRoleService(roleRepo)
	userService := userservice.NewUserService(userRepo, roleService)
	userHandler := handlers.NewUserHandler(userService)
	userRoutes := routes.NewUserRoutes(userHandler)
	return userRoutes
}
