// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infras

import (
	"crawler/handlers"
	"crawler/repository"
	"crawler/services/article"
	"crawler/services/articlesSource"
	"crawler/services/crawler"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitizeGRPCServer(db *gorm.DB) *handlers.GRPCServer {
	crawlerRepo := repository.NewCrawlerRepo(db)
	articleRepo := repository.NewArticleRepo(db)
	articleService := articleservices.NewArticleService(articleRepo)
	articlesSourcesRepo := repository.NewArticlesSourcesRepo(db)
	articlesSourceService := articlessourceservices.NewArticlesSourceService(articlesSourcesRepo)
	crawlerService := crawlerservices.NewCrawlerService(crawlerRepo, articleService, articlesSourceService)
	grpcServer := handlers.NewGRPCServer(crawlerService)
	return grpcServer
}
