// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "server/entities"
	services "server/services"

	mock "github.com/stretchr/testify/mock"
)

// CategoryServices is an autogenerated mock type for the CategoryServices type
type CategoryServices struct {
	mock.Mock
}

// Count provides a mock function with given fields:
func (_m *CategoryServices) Count() (int, error) {
	ret := _m.Called()

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateIfNotExist provides a mock function with given fields: role, category
func (_m *CategoryServices) CreateIfNotExist(role string, category entities.Category) error {
	ret := _m.Called(role, category)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, entities.Category) error); ok {
		r0 = rf(role, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: role, category
func (_m *CategoryServices) Delete(role string, category entities.Category) error {
	ret := _m.Called(role, category)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, entities.Category) error); ok {
		r0 = rf(role, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPagination provides a mock function with given fields: page, pageSize
func (_m *CategoryServices) GetPagination(page int, pageSize int) ([]services.CategoryResponse, error) {
	ret := _m.Called(page, pageSize)

	var r0 []services.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]services.CategoryResponse, error)); ok {
		return rf(page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int, int) []services.CategoryResponse); ok {
		r0 = rf(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields:
func (_m *CategoryServices) ListAll() ([]services.CategoryResponse, error) {
	ret := _m.Called()

	var r0 []services.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]services.CategoryResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []services.CategoryResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListName provides a mock function with given fields:
func (_m *CategoryServices) ListName() ([]services.CategoryResponse, error) {
	ret := _m.Called()

	var r0 []services.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]services.CategoryResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []services.CategoryResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: role, payload
func (_m *CategoryServices) Update(role string, payload services.UpdateNameCategoryPayload) error {
	ret := _m.Called(role, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, services.UpdateNameCategoryPayload) error); ok {
		r0 = rf(role, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoryServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryServices creates a new instance of CategoryServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryServices(t mockConstructorTestingTNewCategoryServices) *CategoryServices {
	mock := &CategoryServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
