// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadLaterServices is an autogenerated mock type for the ReadLaterServices type
type ReadLaterServices struct {
	mock.Mock
}

// AddToReadLaterList provides a mock function with given fields: username, articleID
func (_m *ReadLaterServices) AddToReadLaterList(username string, articleID uint) error {
	ret := _m.Called(username, articleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = rf(username, articleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFromReadLaterList provides a mock function with given fields: username, articleID
func (_m *ReadLaterServices) RemoveFromReadLaterList(username string, articleID uint) error {
	ret := _m.Called(username, articleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = rf(username, articleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewReadLaterServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewReadLaterServices creates a new instance of ReadLaterServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReadLaterServices(t mockConstructorTestingTNewReadLaterServices) *ReadLaterServices {
	mock := &ReadLaterServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
